name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      SubscriptionId:
        description: 'Subscription ID'
        required: true
        type: string
      SubscriptionName:
        description: 'Subscription Name'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to Azure
    - name: Log in to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Install backend dependencies
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # Run backend tests
    - name: Run backend tests
      run: |
        cd backend
        npm test

    # Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    # Run frontend tests
    - name: Run frontend tests
      run: |
        cd frontend
        npm test

    # Build frontend
    - name: Build frontend
      run: |
        cd frontend
        npm run build

    # Create target directory for frontend build in backend
    - name: Create target directory
      run: |
        mkdir -p backend/build

    # Copy frontend build to backend
    - name: Copy frontend build to backend
      run: |
        cp -r frontend/build/* backend/build

    # Deploy backend to Azure Web App
    - name: Deploy to Azure Web App (Backend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flag-explorer-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: ./backend

    # Deploy frontend to Azure Web App
    - name: Deploy to Azure Web App (Frontend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flag-explorer-frontend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: ./frontend/build